# Generated by Django 6.0 on 2026-02-16 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_booking_paid_booking_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='razorpay_signature',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
