# Generated by Django 6.0 on 2026-02-17 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_booking_razorpay_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tours',
            name='tours_img',
            field=models.ImageField(upload_to='tours/'),
        ),
    ]
