# Generated by Django 6.0.3 on 2026-03-16 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_hotel_city_booking_invoice_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('base_price', models.FloatField()),
                ('room_price', models.FloatField(default=0)),
                ('subtotal', models.FloatField()),
                ('discount_percent', models.PositiveSmallIntegerField(default=0)),
                ('discount_amount', models.FloatField(default=0)),
                ('gst_amount', models.FloatField(default=0)),
                ('amount_paid', models.FloatField()),
                ('order_id', models.CharField(blank=True, max_length=200, null=True)),
                ('payment_id', models.CharField(blank=True, max_length=200, null=True)),
                ('payment_signature', models.CharField(blank=True, max_length=200, null=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='app.booking')),
            ],
        ),
    ]
