# Generated by Django 6.0 on 2026-05-09 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_traveler'),
    ]

    operations = [
        migrations.AddField(
            model_name='traveler',
            name='age',
            field=models.PositiveIntegerField(default=25),
            preserve_default=False,
        ),
    ]
